version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
          name: build
      - run:
          command: npm run publish
          name: publish
      - run:
          command: npm run deploy
          name: deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
