version: 2.1
workflows:
  publish:
    jobs:
      - deploy:
          docker:
            - image: cimg/node:16.14.2
          steps:
            - checkout
            - run: 'npm i'
            - run: 'npm publish'
